pip3 install fastapi_jwt_auth


Generate secreate key 

1 ) open terminal type ( python3 )
2 ) import secrets
3 ) secrets.tiken_hex()


++++++++++++++++++++++++ main.py ++++++++++++++
from fastapi_jwt_auth import AuthJWT
from schemas import Settings
@AuthJWT.load_config
def get_config():
    return Settings()
    
    
++++++++++++++++++++++++ schemas.py +++++++++++++++++++

# for jwt +++++

class Settings(BaseModel):
    authjwt_secret_key:str="e13df595946d7818f3d4839c05f5e992126566ca3a808f47bf8293f9baaa1e5f"

class LoginModel(BaseModel):
    username:str
    password:str
    


++++++++ auth_routes.py +++++++++++++++++++

from fastapi_jwt_auth import AuthJWT
from fastapi.encoders import jsonable_encoder
from fastapi.exceptions import HTTPException
from schemas import SignUpModel,LoginModel
from schemas import SignUpModel , LoginModel 
from fastapi import  APIRouter , status , Depends


@auth_router.post('/login',status_code=200)
async def login(user:LoginModel,Authorize:AuthJWT=Depends()):

    db_user=session.query(User).filter(User.username==user.username).first()

    if db_user and check_password_hash(db_user.password, user.password):
        access_token=Authorize.create_access_token(subject=db_user.username)
        refresh_token=Authorize.create_refresh_token(subject=db_user.username)

        response={
            "access":access_token,
            "refresh":refresh_token
        }

        return jsonable_encoder(response)

    raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
        detail="Invalid Username Or Password"
    )
    
